title: Manish Patil
email: patilmanish.ofc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: patil8982
github_username:  jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Build settings
minimal_mistakes_skin: "dark"
teaser: /assets/images/500x300.png/pp.png
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

include: ["_pages", "_posts", "_books", "_tech", "_collection", "_blogs"]

# Site Author
author:
  name             : "Manish Patil"
  avatar           : "/manish.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "DevOps Engineer at Amadeus"
  location         : "South Banglore, India"
  email            : "patilmanish.ofc@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ManishPatilx"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : ""
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "patil8982"
  vine             :
  weibo            :
  xing             :
  youtube          :

collections:
  books:
    output: true
    permalink: /:collection/:path/
  blogs:
    output: true
    permalink: /:collection/:path/
  tech:
    output: true
    permalink: /:collection/:path/
  collection:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true # true
      share: true
      related: true
  - scope:
      path: ""
      type: books
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: blogs
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      teaser: /pp.png
